from __future__ import annotations

from src.llm.openai_client import OpenAIClient
from src.models.domain import (
    ActivityDiagram,
    ActivityPlan,
    Requirement,
)


class GeneratorAgent:

    def __init__(
        self,
        llm: OpenAIClient,
    ) -> None:

        self.llm = llm

    def run(
        self,
        requirement_text: str,
        requirements: list[Requirement],
        plan: ActivityPlan,
    ) -> ActivityDiagram:

        system = """
You are an expert UML Activity Diagram model generator.

Convert the supplied ActivityPlan into a canonical ActivityDiagram.

IMPORTANT:

The ActivityPlan is authoritative.

Do NOT invent new workflow behavior.

Do NOT remove behavior from the plan.

Preserve the explicit decisions, loops, concurrency,
exceptions and termination strategy.

Generate an intermediate Activity Diagram graph.

Use these node types:

initial
final
action
decision
merge
fork
join
object
note

Use these edge types:

control
object

Every node must contain:

id
type
label
requirement_ids

Every edge must contain:

id
source
target
type
guard
requirement_ids

Requirements:

- Start with exactly one initial node.
- End with at least one final node.
- Decision nodes must have guarded outgoing edges.
- Fork nodes must have at least two outgoing branches.
- Join nodes synchronize parallel branches.
- Preserve all requirement IDs.
- Use [] when there is no requirement mapping.
- Use null for an edge without a guard.

The resulting graph is an intermediate representation.
PlantUML will be generated by a deterministic compiler later.
"""

        user = f"""
ORIGINAL REQUIREMENTS:

{requirement_text}


ATOMIC REQUIREMENTS:

{[r.model_dump() for r in requirements]}


ACTIVITY PLAN:

{plan.model_dump()}


Generate the complete ActivityDiagram.
"""

        return self.llm.complete(
            system=system,
            user=user,
            response_model=ActivityDiagram,
        )